FROM quay.io/coreos-assembler/coreos-assembler:latest as builder
ARG MANIFEST=manifest.yaml
USER root
WORKDIR /workdir
ENV COSA_NO_KVM=1
ENV COSA_SKIP_OVERLAY=1
RUN --mount=type=bind,rw=true,src=.,dst=/buildcontext,bind-propagation=shared \
      curl --fail -L "http://base-4-18-rhel94.ocp.svc.cluster.local" -o "/buildcontext/ocp.repo" && \
      ls -l /dev && findmnt && cosa init --force /buildcontext && cosa fetch && cosa build ostree && \
      mv -v builds/latest/$(arch)/*.ociarchive /buildcontext/out.ociarchive

FROM oci-archive:out.ociarchive
# Need to reference builder here to force ordering. But since we have to run
# something anyway, we might as well cleanup after ourselves.
RUN --mount=type=bind,from=builder,src=.,target=/var/tmp \
    --mount=type=bind,rw=true,src=.,dst=/buildcontext,bind-propagation=shared \
      rm /buildcontext/out.ociarchive
